(defpackage #:cl-dns
  (:use #:cl)
  (:export
           #:*record-types*
           #:add-trust-anchor
           #:cache-load
           #:cache-lookup
           #:cache-purge
           #:cache-save
           #:cache-store
           #:connection-pool
           #:decode-message
           #:decode-name
           #:deduplicate-query
           #:discover-services
           #:dns-cache
           #:dns-error
           #:dns-header
           #:dns-message
           #:dns-nxdomain
           #:dns-question
           #:dns-rr
           #:dns-servfail
           #:dns-timeout
           #:dns-update
           #:doh-query
           #:dot-query
           #:encode-message
           #:encode-name
           #:happy-eyeballs
           #:make-dns-cookie
           #:make-opt-rr
           #:make-query
           #:mdns-query
           #:pool-close-all
           #:query-deduplicator
           #:resolve
           #:resolve-iterative
           #:resolve-parallel
           #:resolver
           #:send-query
           #:tcp-transport
           #:tls-transport
           #:trust-anchor-store
           #:tsig-sign
           #:tsig-verify
           #:udp-transport
           #:validate-dnssec
           #:verify-denial
           #:verify-rrsig
           #:zone-transfer
           #:zone-transfer-incremental))
