(in-package #:cl-dns)

(defgeneric send-query (transport query-bytes &key timeout)
  (:documentation "Generic transport protocol for sending DNS queries."))
(defclass tcp-transport ()
  ((host :initarg :host :accessor transport-host)
   (port :initarg :port :initform 53 :accessor transport-port))
  (:documentation "TCP transport for DNS queries."))
(defclass udp-transport ()
  ((host :initarg :host :accessor transport-host)
   (port :initarg :port :initform 53 :accessor transport-port))
  (:documentation "UDP transport for DNS queries."))
(defclass tls-transport ()
  ((host :initarg :host :accessor transport-host)
   (port :initarg :port :initform 853 :accessor transport-port)
   (pool :initarg :pool :initform nil :accessor transport-pool))
  (:documentation "TLS transport for DNS-over-TLS queries."))
